# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.ico"

[footer]
    since = 2024
    customText = ""

[dateFormat]
    published = "2006/01/02"
    lastUpdated = "2006/01/02 15:04:05"

[sidebar]
    emoji = "ğŸ§ "
    subtitle = "hals/ã¯ã‚‹ã™ æƒ…å ±ç³»å¤§å­¦é™¢ç”Ÿã§ã™ã€‚"

    [sidebar.avatar]
        enabled = true
        local = true
        src = "img/Lagtrain.png"

[article]
    headingAnchor = false
    math = true
    readingTime = true

    [article.license]
        enabled = false
        default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
    type = "search"

[[widgets.homepage]]
    type = "archives"

    [widgets.homepage.params]
        limit = 5

[[widgets.homepage]]
    type = "categories"

    [widgets.homepage.params]
        limit = 10

[[widgets.homepage]]
    type = "tag-cloud"

    [widgets.homepage.params]
        limit = 10

[[widgets.page]]
    type = "toc"

[opengraph.twitter]
    site = ""
    card = "summary"

[defaultImage.opengraph]
    enabled = true
    local = false
    src = "avatar.jpg"

[colorScheme]
    toggle = true
    default = "auto"

[imageProcessing.cover]
    enabled = true

[imageProcessing.content]
    enabled = true
